# Generated by Django 4.2.9 on 2024-01-19 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_rename_card_cards'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cards',
            new_name='Card',
        ),
    ]
