# Generated by Django 4.2.9 on 2024-01-23 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_rename_cards_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='game_session',
        ),
        migrations.AddField(
            model_name='gamesession',
            name='cards',
            field=models.ManyToManyField(related_name='cards', to='games.card'),
        ),
    ]
